import { useNuxt } from '@nuxt/kit'
import { resolve } from 'node:path'

export function useAppColors(): Record<string, string> {
  return require(resolve(useNuxt().options.buildDir, 'autogenerated/client/theme/theme.colors.ts').replace(/\\/g, '/'))
}
